# Generated by Django 3.0 on 2019-12-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand_supply',
            fields=[
                ('home_id', models.IntegerField(primary_key=True, serialize=False)),
                ('demand', models.FloatField(default=0, null=True)),
                ('supply', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
