# Generated by Django 3.0 on 2020-02-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='BDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='CitizenshipNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
